version: '3'

services:
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: ci_cd_metrics
      INFLUXDB_USER: admin
      INFLUXDB_USER_PASSWORD: admin
    volumes:
      - influxdb_data:/var/lib/influxdb2
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus  # Volume pour persister les données de Prometheus

    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Définissez un mot de passe pour Grafana ici
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana  # Volume pour persister les données de Grafana


networks:
  monitoring:
    driver: bridge
volumes:
  grafana-data:  # Déclaration du volume nommé pour Grafana
  influxdb_data:  # Déclaration du volume nommé pour InfluxDB
  prometheus_data:  # Déclaration du volume nommé pour Prometheus
