version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysqlDevops-db
    environment:
      MYSQL_DATABASE: Foyer
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"  # Changez 3306:3306 à 3307:3306

  springboot-app:
    image: hedilinux/projetdevopsimg:latest
    container_name: springboot-app
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/Foyer?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8088:8088"
    depends_on:
      - mysql

volumes:
  mysql-data:
