version: "3"

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.55.0
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - ./data:/prmetheus

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:11.3.0
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
