version: '3'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: ci_cd_metrics
      INFLUXDB_USER: admin
      INFLUXDB_USER_PASSWORD: admin
    volumes:
      - influxdb-storage:/var/lib/influxdb2
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin  # Mot de passe administrateur pour Grafana
    depends_on:
      - prometheus
      - influxdb
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  influxdb-storage:
  prometheus-storage:
  grafana-storage:
