apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-devops-pvc  # Nom modifié en minuscules avec des tirets
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
