global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['20.0.0.21:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
