global:
  scrape_interval: 15s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "jenkins"
    scrape_interval: 5s
    static_configs:
      - targets: ["192.168.56.10:8080"]
    metrics_path: /prometheus
